#version 460

layout(local_size_x = 64, local_size_y = 1, local_size_z = 1) in;

// Match the c++ struct
struct Particle {
    vec4 positionLife;
    vec4 velocitySize;
    vec4 color;
    vec4 initPosLife;
    vec3 initVelocity;
};

// Storage buffer for particle data (r/w)
layout(std430, binding = 0) buffer ParticleBuffer {
    uint particleCount;
    Particle particles[];
} particleBuffer;

layout(binding = 1) uniform SimulationParams {
    vec4 gravityDeltaTime;
    vec4 windDamping;
    vec4 particlesPosLife;
} params;

void main() {
    uint index = gl_GlobalInvocationID.x;

    if (index >= particleBuffer.particleCount) return;

    Particle p = particleBuffer.particles[index];

    // Reset dead particles
    if (p.positionLife.w <= 0.0) {
        p.positionLife = p.initPosLife;  // emitter position (should be passed as uniform)
        p.velocitySize.xyz = p.initVelocity;
        particleBuffer.particles[index] = p;
        return;
    }

    // Update velocity and forces
    p.velocitySize += vec4(params.gravityDeltaTime.xyz * params.gravityDeltaTime.w, 0.0);
    p.velocitySize += vec4(params.windDamping.xyz * params.gravityDeltaTime.w, 0.0);
    p.velocitySize.xyz *= pow(params.windDamping.w, params.gravityDeltaTime.w);

    // upd position
    p.positionLife += vec4(p.velocitySize.xyz * params.gravityDeltaTime.w, 0.0);

    // upd lifetime
    p.positionLife.w -= params.gravityDeltaTime.w;

    // Simple floor collision
    // if (p.positionLife.y < 0.0) {
    //     p.positionLife.y = 0.0;
    //     p.velocitySize.y *= -1.3; // Bounce with energy gain
    // }

    // Write back updated particle
    particleBuffer.particles[index] = p;
}